# Generated by Django 4.2.15 on 2024-09-06 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_onetimedeposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeHavenPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=30)),
                ('sessionId', models.CharField(max_length=40)),
                ('creditAccountNumber', models.CharField(max_length=10)),
                ('creditAccountName', models.CharField(max_length=100)),
                ('debitAccountNumber', models.CharField(max_length=20)),
                ('debitAccountName', models.CharField(max_length=100)),
                ('paymentReference', models.CharField(max_length=200)),
                ('narration', models.CharField(max_length=200)),
                ('transactionAmount', models.CharField(max_length=10)),
                ('settledAmount', models.CharField(max_length=10)),
                ('feeAmount', models.CharField(max_length=10)),
                ('vatAmount', models.CharField(max_length=10)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('tranDateTime', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
