# Generated by Django 4.2.15 on 2024-09-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_partnerbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAccountBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main', max_length=10)),
                ('active_backend', models.CharField(choices=[('SafeHaven MFB', 'SafeHaven MFB')], default='SafeHaven MFB', max_length=20)),
            ],
        ),
    ]
