# Generated by Django 4.2.15 on 2024-09-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_dynamicaccountbackend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimedeposit',
            name='settledAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
