# Generated by Django 4.2.15 on 2024-08-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_Code',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
