# Generated by Django 4.2.15 on 2024-08-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_referral_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referral_Code',
            new_name='referral_code',
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
