# Generated by Django 4.2.15 on 2024-08-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmation',
            name='confirmation_type',
            field=models.CharField(choices=[('Email', 'Email'), ('OTP', 'OTP')], default='Email', max_length=10),
        ),
    ]
