# Generated by Django 4.2.15 on 2024-08-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userconfirmation_confirmation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_attempts_left',
            field=models.IntegerField(default=3),
        ),
    ]
