# Generated by Django 4.2.15 on 2024-08-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='APIreference',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Initiating', 'Initiating'), ('Success', 'Success'), ('Refunded', 'Refunded')], default='Initiating', max_length=12),
        ),
    ]
