# Generated by Django 4.2.15 on 2024-08-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_cashback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Success', 'Success'), ('Refunded', 'Refunded')], default='Processing', max_length=12),
        ),
    ]
