# Generated by Django 4.2.15 on 2024-08-29 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='APIBackend',
            field=models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Cable', 'Cable'), ('Electricity', 'Electricity')], default='-', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='last_transacted',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walletactivity',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
