# Generated by Django 4.2.15 on 2024-08-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_transaction_apibackend_user_last_transacted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletactivity',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
