# Generated by Django 4.2.15 on 2024-09-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_kycdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_transacted',
            field=models.DateField(default=''),
        ),
    ]
