# Generated by Django 4.2.15 on 2024-09-06 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_last_transacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_transacted',
            field=models.DateField(verbose_name=datetime.date(2024, 9, 6)),
        ),
    ]
