# Generated by Django 4.2.15 on 2024-09-06 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_last_transacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_transacted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
