# Generated by Django 4.2.15 on 2024-09-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_last_transacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletactivity',
            name='transaction_type',
            field=models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Cable', 'Cable'), ('Electricity', 'Electricity'), ('Top Up', 'Top Up'), ('Admin Top Up', 'Admin Top Up'), ('Cashback Withdrwal', 'Cashback Withdrwal'), ('Referral Bonus', 'Referral Bonus')], max_length=20),
        ),
    ]
