# Generated by Django 4.2.15 on 2024-09-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_walletactivity_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='VPSAccount_reassigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='bvn_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_VPSAccount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_safeHavenAccount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='nin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='safeHavenAccount_account_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='safeHavenAccount_account_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='vps_account_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
