# Generated by Django 4.2.15 on 2024-09-06 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_vpsaccount_reassigned_user_bvn_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeHavenAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10)),
                ('account_name', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=30)),
                ('bank_name', models.CharField(default='SafeHaven MFB', max_length=100)),
                ('external_Reference', models.CharField(max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_funded', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
