# Generated by Django 4.2.15 on 2024-10-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_beneficiary_cable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='token_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='APIBackend',
            field=models.CharField(choices=[('ATN', 'ATN'), ('TWINS10', 'TWINS10'), ('HONOURWORLD', 'HONOURWORLD')], default='-', max_length=15),
        ),
    ]
