# Generated by Django 4.2.15 on 2024-10-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_transaction_token_transaction_token_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='token_units',
            new_name='electricity_units',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='APIBackend',
            field=models.CharField(choices=[('ATN', 'ATN'), ('TWINS10', 'TWINS10'), ('HONOURWORLD', 'HONOURWORLD'), ('9Payment', '9Payment')], default='-', max_length=15),
        ),
    ]
