# Generated by Django 4.2.15 on 2024-10-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_rename_token_units_transaction_electricity_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customerName',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='electricity_units',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
