# Generated by Django 4.2.15 on 2024-10-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_transaction_customername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customerAddress',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customerName',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='electricity_units',
            field=models.CharField(default='-', max_length=25),
        ),
    ]
