# Generated by Django 4.2.15 on 2024-10-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_transaction_customeraddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='package',
            field=models.CharField(max_length=100),
        ),
    ]
