# Generated by Django 4.2.15 on 2024-10-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_transaction_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='bet_funding',
            field=models.JSONField(default=list),
        ),
    ]
