# Generated by Django 4.2.15 on 2024-10-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_beneficiary_bet_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_offers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='cashback',
            name='transaction_type',
            field=models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Cable', 'Cable'), ('Electricity', 'Electricity'), ('Bet Funding', 'Bet Funding')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Cable', 'Cable'), ('Electricity', 'Electricity'), ('Bet Funding', 'Bet Funding')], max_length=20),
        ),
        migrations.AlterField(
            model_name='walletactivity',
            name='transaction_type',
            field=models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Cable', 'Cable'), ('Electricity', 'Electricity'), ('Bet Funding', 'Bet Funding'), ('Top Up', 'Top Up'), ('Admin Top Up', 'Admin Top Up'), ('Cashback Withdrwal', 'Cashback Withdrwal'), ('Referral Bonus', 'Referral Bonus')], max_length=20),
        ),
    ]
