# Generated by Django 4.2.15 on 2024-10-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_user_give_away_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletactivity',
            name='transaction_type',
            field=models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Cable', 'Cable'), ('Electricity', 'Electricity'), ('Bet Funding', 'Bet Funding'), ('Top Up', 'Top Up'), ('Admin Top Up', 'Admin Top Up'), ('Cashback Withdrwal', 'Cashback Withdrwal'), ('Referral Bonus', 'Referral Bonus'), ('Give-Away', 'Give-Away')], max_length=20),
        ),
    ]
