# Generated by Django 4.2.15 on 2024-10-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_walletactivity_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashback',
            name='transaction_type',
            field=models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Cable', 'Cable'), ('Electricity', 'Electricity'), ('Bet Funding', 'Bet Funding'), ('Internet', 'Internet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Cable', 'Cable'), ('Electricity', 'Electricity'), ('Bet Funding', 'Bet Funding'), ('Internet', 'Internet')], max_length=20),
        ),
    ]
