# Generated by Django 4.2.15 on 2024-10-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_cashback_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operator',
            field=models.CharField(max_length=25),
        ),
    ]
