# Generated by Django 4.2.15 on 2024-10-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_transaction_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='education',
            field=models.JSONField(default=list),
        ),
    ]
