# Generated by Django 4.2.15 on 2024-10-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_beneficiary_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashback',
            name='transaction_type',
            field=models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Cable', 'Cable'), ('Electricity', 'Electricity'), ('Bet Funding', 'Bet Funding'), ('Internet', 'Internet'), ('Education', 'Education')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Cable', 'Cable'), ('Electricity', 'Electricity'), ('Bet Funding', 'Bet Funding'), ('Internet', 'Internet'), ('Education', 'Education')], max_length=20),
        ),
        migrations.AlterField(
            model_name='walletactivity',
            name='transaction_type',
            field=models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Cable', 'Cable'), ('Electricity', 'Electricity'), ('Bet Funding', 'Bet Funding'), ('Internet', 'Internet'), ('Education', 'Education'), ('Top Up', 'Top Up'), ('Admin Top Up', 'Admin Top Up'), ('Cashback Withdrwal', 'Cashback Withdrwal'), ('Referral Bonus', 'Referral Bonus'), ('Give-Away', 'Give-Away')], max_length=20),
        ),
    ]
