# Generated by Django 4.2.15 on 2024-10-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_cashback_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='education_data',
            field=models.JSONField(default=dict),
        ),
    ]
