# Generated by Django 4.2.15 on 2024-10-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_transaction_education_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completed_offers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
