# Generated by Django 4.1.7 on 2024-10-30 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_user_completed_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stories_images')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.story')),
            ],
        ),
    ]
