# Generated by Django 4.1.7 on 2024-10-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_story_image_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='zip_files/')),
            ],
        ),
    ]
