# Generated by Django 4.1.7 on 2024-10-31 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_zipfilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryImage',
        ),
    ]
