# Generated by Django 4.1.7 on 2024-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_delete_storyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount_genarated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
