# Generated by Django 4.1.7 on 2024-11-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_user_discount_genarated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unit_cost',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
