# Generated by Django 4.1.7 on 2024-12-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_user_notification_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, default='-', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_key_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_key_timedout',
            field=models.BooleanField(default=True),
        ),
    ]
