# Generated by Django 4.1.7 on 2025-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletactivity',
            name='transaction_type',
            field=models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Cable', 'Cable'), ('Electricity', 'Electricity'), ('Bet Funding', 'Bet Funding'), ('Internet', 'Internet'), ('Education', 'Education'), ('Top Up', 'Top Up'), ('Admin Top Up', 'Admin Top Up'), ('Admin Deduction', 'Admin Deduction'), ('Cashback Withdrwal', 'Cashback Withdrwal'), ('Referral Bonus', 'Referral Bonus'), ('Give-Away', 'Give-Away')], max_length=20),
        ),
    ]
