# Generated by Django 4.1.7 on 2025-02-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_walletactivity_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletactivity',
            name='event_user',
            field=models.CharField(default='Transaction', max_length=40),
        ),
    ]
