# Generated by Django 4.2.15 on 2024-10-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillPaymentServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Cable', 'Cable'), ('Electricity', 'Electricity')], max_length=15)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
