# Generated by Django 4.2.15 on 2024-08-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecomms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirtimeTransaction',
        ),
    ]
