# Generated by Django 4.2.15 on 2024-08-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telecomms', '0002_delete_airtimetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATNDataPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_operator', models.CharField(choices=[('MTN', 'MTN'), ('Glo', 'Glo'), ('Airtel', 'Airtel'), ('9Mobile', '9Mobile')], max_length=10)),
                ('plan', models.CharField(default='', max_length=50)),
                ('package_id', models.CharField(max_length=50)),
                ('vendor_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DataServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_operator', models.CharField(choices=[('MTN', 'MTN'), ('Glo', 'Glo'), ('Airtel', 'Airtel'), ('9Mobile', '9Mobile')], max_length=10)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
