# Generated by Django 4.2.15 on 2024-08-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecomms', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtimeServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_operator', models.CharField(choices=[('MTN', 'MTN'), ('Glo', 'Glo'), ('Airtel', 'Airtel'), ('9Mobile', '9Mobile')], max_length=10)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
