# Generated by Django 4.2.15 on 2024-08-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecomms', '0005_honouworlddatadiscount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HonouworldDataDiscount',
            new_name='HonouworldDataPlans',
        ),
    ]
