# Generated by Django 4.2.15 on 2024-09-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecomms', '0007_twins10dataplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='atndataplans',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='atndataplans',
            name='list_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atndataplans',
            name='plan_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Extra', 'Extra')], default='Normal', max_length=10),
        ),
    ]
