# Generated by Django 4.2.15 on 2024-09-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecomms', '0008_atndataplans_available_atndataplans_list_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honouworlddataplans',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='honouworlddataplans',
            name='list_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twins10dataplans',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='twins10dataplans',
            name='list_order',
            field=models.IntegerField(default=0),
        ),
    ]
