# Generated by Django 4.2.15 on 2024-08-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Transfer', 'Transfer'), ('Cashback', 'Cashback'), ('Referral Bonus', 'Referral Bonus'), ('Failed Deposit', 'Failed Deposit')], default='Transfer', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balanceBefore', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balanceAfter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sessionId', models.CharField(max_length=200)),
                ('accountNumber', models.CharField(max_length=10)),
                ('sourceAccountNumber', models.CharField(max_length=20)),
                ('sourceAccountName', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
