# Generated by Django 4.2.15 on 2024-08-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletFunding',
        ),
    ]
