# Generated by Django 4.2.15 on 2024-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminbackend', '0002_delete_walletfunding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtimeBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default='Main', max_length=10)),
                ('active_backend', models.CharField(choices=[('ATN', 'ATN'), ('TWINS10', 'TWINS10'), ('HONOURWORLD', 'HONOURWORLD')], default='ATN', max_length=15)),
            ],
        ),
    ]
