# Generated by Django 4.2.15 on 2024-08-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtimeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkOperator', models.CharField(choices=[('MTN', 'MTN'), ('Glo', 'Glo'), ('9Mobile', '9Mobile'), ('Airtel', 'Airtel')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
