# Generated by Django 4.2.15 on 2024-08-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0005_databackend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databackend',
            name='operator',
            field=models.CharField(choices=[('MTN', 'MTN'), ('Glo', 'Glo'), ('9Mobile', '9Mobile'), ('Airtel', 'Airtel')], max_length=10),
        ),
    ]
