# Generated by Django 4.2.15 on 2024-10-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0006_alter_databackend_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main', max_length=10)),
                ('active_backend', models.CharField(choices=[('ATN', 'ATN'), ('TWINS10', 'TWINS10'), ('HONOURWORLD', 'HONOURWORLD')], default='9Payment', max_length=15)),
            ],
        ),
    ]
