# Generated by Django 4.2.15 on 2024-10-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0012_alter_electricitybackend_active_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablebackend',
            name='active_backend',
            field=models.CharField(choices=[('9Payment', '9Payment'), ('SafeHaven', 'SafeHaven')], default='9Payment', max_length=15),
        ),
    ]
