# Generated by Django 4.1.7 on 2024-10-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0013_alter_cablebackend_active_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuvustory',
            name='description',
            field=models.CharField(default='He started blackmailing her with her nude', max_length=100),
            preserve_default=False,
        ),
    ]
