# Generated by Django 4.1.7 on 2024-11-02 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0014_vuvustory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuvustory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
