# Generated by Django 4.1.7 on 2024-11-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0015_vuvustory_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillServicesDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Electricity', 'Electricity'), ('Cable', 'Cable'), ('Education', 'Education'), ('Betting', 'Betting')], max_length=25)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
