# Generated by Django 4.1.7 on 2024-12-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0016_billservicesdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Notice', max_length=20)),
                ('link', models.CharField(blank=True, default='#', max_length=800)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
